import { AccountAuth } from "@/components/account-auth";
import { AccountSessionProvider } from "@/components/account-session";
import { AgentConnections } from "@/components/agent-connections";
import { ServiceCatalog } from "@/components/service-catalog";
import { SystemStatus } from "@/components/system-status";
import { DemoScenarios } from "@/components/demo-scenarios";
import { policyEvidence } from "@/lib/submission-evidence";

const flow = ["402", "Quote", "Policy", "Human approval", "Razorpay", "Entitlement", "Result"];


function Navigation() {
  return <nav className="site-nav" aria-label="Primary navigation"><div className="site-container site-nav-inner"><a className="site-wordmark" href="#top">MeterGate</a><div className="site-links"><a href="#product">Product</a><a href="#agent-flow">Agent Flow</a><a href="#security">Security</a><a href="#developer">Developer</a><a href="/operator">Operator</a></div><div className="site-nav-actions"><a className="site-nav-action" href="#buyer-account">Sign in</a><a className="site-nav-action primary" href="#demo-guide">View Demo</a></div></div></nav>;
}

export default function Home() {
  return <div id="top" className="minimal-shell"><Navigation/><main>
    <section className="hero"><div className="site-container"><p className="eyebrow">Agent commerce infrastructure · Razorpay Test Mode</p><h1>Make your API sellable to AI.</h1><p className="hero-copy">MeterGate lets AI agents discover, authorize, pay for, and access digital services through Razorpay — without giving agents unrestricted payment authority.</p><div className="hero-actions"><a className="button primary" href="#demo-guide">Try the guided demo</a><a className="button" href="#developer">View architecture</a></div><p className="principle">AI proposes. Deterministic systems authorize. Humans approve.</p><div className="infra-flow" aria-label="MeterGate commerce sequence">{flow.map(step=><div className="flow-step" key={step}>{step}</div>)}</div></div></section>
    <DemoScenarios />
    <div id="live-demo" className="site-container"><AccountSessionProvider><AccountAuth/><AgentConnections/><ServiceCatalog/></AccountSessionProvider><SystemStatus/></div>
    <section id="product" className="content-section"><div className="site-container"><div className="section-head"><h2>Commerce primitives, not payment authority.</h2><p>MeterGate translates a protected API into a machine-readable purchase path while keeping price, policy, approval, payment verification, and value release inside deterministic boundaries.</p></div><div className="three-up"><div className="feature"><h3>Machine-readable commerce</h3><p>Structured 402 responses lead agents to server-priced quotes and explicit next actions.</p></div><div className="feature"><h3>Bounded money authority</h3><p>Immutable policies evaluate amount, currency, merchant, service, and purchase type.</p></div><div className="feature"><h3>Verified value release</h3><p>Captured payment produces a narrow entitlement before protected fulfillment can run.</p></div></div></div></section>
    <section id="agent-flow" className="content-section"><div className="site-container"><div className="section-head"><h2>AI can act. Authority stays bounded.</h2><p>Deterministic policy, passkey approval, Proof of Human Presence, verified capture, and entitlement-bound access remain separate, observable stages.</p></div><div className="technical-grid"><ul className="technical-list"><li><span>Deterministic policy</span><code>ALLOW / DENY</code></li><li><span>Passkey approval</span><code>userVerification=required</code></li><li><span>Proof of Human Presence</span><code>action-bound · short-lived</code></li><li><span>Payment capture</span><code>backend verified</code></li><li><span>Access</span><code>entitlement-bound</code></li></ul><pre className="code-block" aria-label="Actual 402 contract example"><code>{`POST /api/v1/resources/orbitintel/orbital-risk-report/execute\n\n{"norad_id": 25544}\n\n`}<span className="code-status">402 Payment Required</span>{`\n{\n  "type": "metergate_payment_required",\n  "protocol": "metergate/1",\n  "payment_provider": "razorpay",\n  "access": {"scheme": "Bearer",\n             "maximum_executions": 1}\n}`}</code></pre></div></div></section>
    <section className="content-section" aria-labelledby="evidence-heading"><div className="site-container"><div className="section-head"><h2 id="evidence-heading">Proof you can inspect.</h2><p>Recorded policy checks and a real Razorpay Test Mode refund. Each result has a date and a defined scope.</p></div><dl className="evidence-cards"><div><dt>Deterministic policy checks</dt><dd>{policyEvidence.passed}/{policyEvidence.scenario_count} passed</dd><p>Recorded {policyEvidence.generated_at.slice(0, 10)} · in-process policy evaluation</p></div><div><dt>Provider-confirmed recovery</dt><dd>₹5 refunded</dd><p>One historical acceptance run · 2026-08-26 · Test Mode</p></div><div><dt>Agent interface</dt><dd>10 narrow tools</dd><p>Discovery and orchestration, with human purchase approval</p></div></dl><a className="button" href="/evidence">Inspect evidence and limitations</a></div></section>
    <section id="security" className="content-section"><div className="site-container"><div className="section-head"><h2>CAPTCHA tests recognition. MeterGate verifies authority.</h2><p>Visual puzzles are increasingly easy for automated systems to solve. MeterGate instead uses short-lived, action-bound passkey verification for sensitive actions. It requires control of a registered authenticator without claiming to be AI-proof.</p></div></div></section>
    <section id="developer" className="content-section"><div className="site-container"><div className="section-head"><h2>Built around explicit contracts.</h2><p>Start from HTTP 402, compose quote and policy APIs, pause at human authority, then resume through capability-scoped execution.</p></div><ul className="technical-list"><li><span>402 contract</span><code>POST /api/v1/resources/…/execute</code></li><li><span>Quote API</span><code>POST /api/v1/quotes</code></li><li><span>MCP interface</span><code>10 narrow buyer tools</code></li><li><span>Capability execution</span><code>Authorization: Bearer &lt;capability&gt;</code></li><li><span>Webhook endpoint</span><code>POST /api/v1/webhooks/razorpay</code></li></ul></div></section>
  </main><footer className="site-footer"><div className="site-container footer-row"><span>MeterGate · agent-readable commerce infrastructure</span><span>Razorpay Test Mode · backend-verified payment state</span></div></footer></div>;
}
